In [4]:
import sqlite3
import pandas as pd
path=r"E:\ds_roadmap\dataset\books_dataset.xlsx"
conn = sqlite3.connect(path)   # opens/creates the .db
conn

In [6]:
import pandas as pd
import sqlite3

# Step 1: Load the Excel file
df_books = pd.read_excel("books_dataset.xlsx")

# Step 2: Connect (or create) SQLite database
conn = sqlite3.connect("books.db")

# Step 3: Save the Excel data as a table named 'books'
df_books.to_sql("books", conn, if_exists="replace", index=False)

# Step 4: Now run your SQL query
df = pd.read_sql_query("SELECT  * FROM books;", conn)
df

,book_id,title,author,genre,year_published,price,rating,publisher,available_copies
0,1,To Kill a Mockingbird,Harper Lee,Fiction,1960,12.99,4.8,J.B. Lippincott & Co.,5
1,2,1984,George Orwell,Dystopian,1949,10.99,4.7,Secker & Warburg,8
2,3,The Great Gatsby,F. Scott Fitzgerald,Classic,1925,11.50,4.6,Charles Scribner's Sons,3
3,4,Pride and Prejudice,Jane Austen,Romance,1813,9.99,4.9,T. Egerton,6
4,5,Moby-Dick,Herman Melville,Adventure,1851,13.99,4.1,Harper & Brothers,4
5,6,The Catcher in the Rye,J.D. Salinger,Fiction,1951,10.50,4.2,"Little, Brown and Company",7
6,7,The Hobbit,J.R.R. Tolkien,Fantasy,1937,15.00,4.9,George Allen & Unwin,10
7,8,Fahrenheit 451,Ray Bradbury,Science Fiction,1953,9.50,4.5,Ballantine Books,9
8,9,Jane Eyre,Charlotte Bronte,Romance,1847,12.00,4.7,"Smith, Elder & Co.",5
9,10,Animal Farm,George Orwell,Satire,1945,8.99,4.8,Secker & Warburg,12
10,11,The Alchemist,Paulo Coelho,Philosophy,1988,14.00,4.6,HarperTorch,11
11,12,The Da Vinci Code,Dan Brown,Thriller,2003,16.50,4.3,Doubleday,14
12,13,Harry Potter and the Sorcerer's Stone,J.K. Rowling,Fantasy,1997,18.99,4.9,Bloomsbury,20
13,14,Brave New World,Aldous Huxley,Dystopian,1932,11.99,4.4,Chatto & Windus,8
14,15,Wuthering Heights,Emily Bronte,Romance,1847,9.50,4.5,Thomas Cautley Newby,6

In [3]:
df=pd.read_sql_query("SELECT  title From books;",conn)
df

                                    title
0                   To Kill a Mockingbird
1                                    1984
2                        The Great Gatsby
3                     Pride and Prejudice
4                               Moby-Dick
5                  The Catcher in the Rye
6                              The Hobbit
7                          Fahrenheit 451
8                               Jane Eyre
9                             Animal Farm
10                          The Alchemist
11                      The Da Vinci Code
12  Harry Potter and the Sorcerer's Stone
13                        Brave New World
14                      Wuthering Heights

In [4]:
df=pd.read_sql_query("SELECT author,title FROM books;",conn)
df

                 author                                  title
0            Harper Lee                  To Kill a Mockingbird
1         George Orwell                                   1984
2   F. Scott Fitzgerald                       The Great Gatsby
3           Jane Austen                    Pride and Prejudice
4       Herman Melville                              Moby-Dick
5         J.D. Salinger                 The Catcher in the Rye
6        J.R.R. Tolkien                             The Hobbit
7          Ray Bradbury                         Fahrenheit 451
8      Charlotte Bronte                              Jane Eyre
9         George Orwell                            Animal Farm
10         Paulo Coelho                          The Alchemist
11            Dan Brown                      The Da Vinci Code
12         J.K. Rowling  Harry Potter and the Sorcerer's Stone
13        Aldous Huxley                        Brave New World
14         Emily Bronte                      Wuthering Heights

In [5]:
df=pd.read_sql_query("SELECT * FROM books Limit 3;",conn)
df

,book_id,title,author,genre,year_published,price,rating,publisher,available_copies
0,1,To Kill a Mockingbird,Harper Lee,Fiction,1960,12.99,4.8,J.B. Lippincott & Co.,5
1,2,1984,George Orwell,Dystopian,1949,10.99,4.7,Secker & Warburg,8
2,3,The Great Gatsby,F. Scott Fitzgerald,Classic,1925,11.50,4.6,Charles Scribner's Sons,3

In [6]:
df=pd.read_sql_query("SELECT  author,title,price FROM books WHERE price > 10.99;",conn)
df

                author                                  title  price
0           Harper Lee                  To Kill a Mockingbird  12.99
1  F. Scott Fitzgerald                       The Great Gatsby  11.50
2      Herman Melville                              Moby-Dick  13.99
3       J.R.R. Tolkien                             The Hobbit  15.00
4     Charlotte Bronte                              Jane Eyre  12.00
5         Paulo Coelho                          The Alchemist  14.00
6            Dan Brown                      The Da Vinci Code  16.50
7         J.K. Rowling  Harry Potter and the Sorcerer's Stone  18.99
8        Aldous Huxley                        Brave New World  11.99

In [7]:
oper=pd.read_sql_query("SELECT author ,title,price,rating From books WHERE (rating > 4.4 or available_copies > 3) AND price > 12.99;",conn)
oper

            author                                  title  price  rating
0  Herman Melville                              Moby-Dick  13.99     4.1
1   J.R.R. Tolkien                             The Hobbit  15.00     4.9
2     Paulo Coelho                          The Alchemist  14.00     4.6
3        Dan Brown                      The Da Vinci Code  16.50     4.3
4     J.K. Rowling  Harry Potter and the Sorcerer's Stone  18.99     4.9

In [8]:
null=pd.read_sql_query("SELECT author,title FROM books WHERE Price IS NOT NULL;",conn)
null

                 author                                  title
0            Harper Lee                  To Kill a Mockingbird
1         George Orwell                                   1984
2   F. Scott Fitzgerald                       The Great Gatsby
3           Jane Austen                    Pride and Prejudice
4       Herman Melville                              Moby-Dick
5         J.D. Salinger                 The Catcher in the Rye
6        J.R.R. Tolkien                             The Hobbit
7          Ray Bradbury                         Fahrenheit 451
8      Charlotte Bronte                              Jane Eyre
9         George Orwell                            Animal Farm
10         Paulo Coelho                          The Alchemist
11            Dan Brown                      The Da Vinci Code
12         J.K. Rowling  Harry Potter and the Sorcerer's Stone
13        Aldous Huxley                        Brave New World
14         Emily Bronte                      Wuthering Heights

In [13]:
like=pd.read_sql_query("SELECT title,author FROM books WHERE title LIKE '%DA%' ;",conn)
like

               title     author
0  The Da Vinci Code  Dan Brown

In [14]:
like=pd.read_sql_query("SELECT title,author FROM books WHERE title LIKE '%LOVE%' ;",conn)
like

Empty DataFrame
Columns: [title, author]
Index: []

In [15]:
like=pd.read_sql_query("SELECT title,author FROM books WHERE title LIKE 'The%' ;",conn)
like

                    title               author
0        The Great Gatsby  F. Scott Fitzgerald
1  The Catcher in the Rye        J.D. Salinger
2              The Hobbit       J.R.R. Tolkien
3           The Alchemist         Paulo Coelho
4       The Da Vinci Code            Dan Brown

In [16]:
like=pd.read_sql_query("SELECT title,author FROM books WHERE title LIKE 'The%Da%' ;",conn)
like

               title     author
0  The Da Vinci Code  Dan Brown

In [20]:
#In case you want to find the Book name whose start with the if yoU write the THE% IT causes minor error becasue it also give the book start as THERE,THEY OR ETC but in the  this formate THE % it gives the correct output#

In [26]:
like=pd.read_sql_query("SELECT title,author FROM books WHERE title LIKE 'The %' ;",conn)
like

                    title               author
0        The Great Gatsby  F. Scott Fitzgerald
1  The Catcher in the Rye        J.D. Salinger
2              The Hobbit       J.R.R. Tolkien
3           The Alchemist         Paulo Coelho
4       The Da Vinci Code            Dan Brown

In [38]:
df = pd.read_sql_query("SELECT title, author FROM books WHERE title LIKE '%G_tsby%';", conn)
df

              title               author
0  The Great Gatsby  F. Scott Fitzgerald

In [40]:
df=pd.read_sql_query("SELECT title ,author,rating FROM books WHERE rating  >=4.4 AND rating <=4.7 ;",conn)
df

               title               author  rating
0               1984        George Orwell     4.7
1   The Great Gatsby  F. Scott Fitzgerald     4.6
2     Fahrenheit 451         Ray Bradbury     4.5
3          Jane Eyre     Charlotte Bronte     4.7
4      The Alchemist         Paulo Coelho     4.6
5    Brave New World        Aldous Huxley     4.4
6  Wuthering Heights         Emily Bronte     4.5

In [42]:
df=pd.read_sql_query("SELECT title ,author,rating FROM books WHERE rating  BETWEEN 4.3 AND 4.6;",conn)
df

               title               author  rating
0   The Great Gatsby  F. Scott Fitzgerald     4.6
1     Fahrenheit 451         Ray Bradbury     4.5
2      The Alchemist         Paulo Coelho     4.6
3  The Da Vinci Code            Dan Brown     4.3
4    Brave New World        Aldous Huxley     4.4
5  Wuthering Heights         Emily Bronte     4.5

In [45]:
df=pd.read_sql_query("SELECT title ,author,rating FROM books  ORDER BY rating DESC",conn)
df

                                    title               author  rating
0                     Pride and Prejudice          Jane Austen     4.9
1                              The Hobbit       J.R.R. Tolkien     4.9
2   Harry Potter and the Sorcerer's Stone         J.K. Rowling     4.9
3                   To Kill a Mockingbird           Harper Lee     4.8
4                             Animal Farm        George Orwell     4.8
5                                    1984        George Orwell     4.7
6                               Jane Eyre     Charlotte Bronte     4.7
7                        The Great Gatsby  F. Scott Fitzgerald     4.6
8                           The Alchemist         Paulo Coelho     4.6
9                          Fahrenheit 451         Ray Bradbury     4.5
10                      Wuthering Heights         Emily Bronte     4.5
11                        Brave New World        Aldous Huxley     4.4
12                      The Da Vinci Code            Dan Brown     4.3
13                 The Catcher in the Rye        J.D. Salinger     4.2
14                              Moby-Dick      Herman Melville     4.1

In [46]:
df=pd.read_sql_query("SELECT title ,author,rating FROM books ORDER BY title DESC ;",conn)
df

                                    title               author  rating
0                       Wuthering Heights         Emily Bronte     4.5
1                   To Kill a Mockingbird           Harper Lee     4.8
2                              The Hobbit       J.R.R. Tolkien     4.9
3                        The Great Gatsby  F. Scott Fitzgerald     4.6
4                       The Da Vinci Code            Dan Brown     4.3
5                  The Catcher in the Rye        J.D. Salinger     4.2
6                           The Alchemist         Paulo Coelho     4.6
7                     Pride and Prejudice          Jane Austen     4.9
8                               Moby-Dick      Herman Melville     4.1
9                               Jane Eyre     Charlotte Bronte     4.7
10  Harry Potter and the Sorcerer's Stone         J.K. Rowling     4.9
11                         Fahrenheit 451         Ray Bradbury     4.5
12                        Brave New World        Aldous Huxley     4.4
13                            Animal Farm        George Orwell     4.8
14                                   1984        George Orwell     4.7

In [48]:
df=pd.read_sql_query("SELECT title ,author,rating,price FROM books ORDER BY rating DESC,Price DESC ;",conn)
df

                                    title               author  rating  price
0   Harry Potter and the Sorcerer's Stone         J.K. Rowling     4.9  18.99
1                              The Hobbit       J.R.R. Tolkien     4.9  15.00
2                     Pride and Prejudice          Jane Austen     4.9   9.99
3                   To Kill a Mockingbird           Harper Lee     4.8  12.99
4                             Animal Farm        George Orwell     4.8   8.99
5                               Jane Eyre     Charlotte Bronte     4.7  12.00
6                                    1984        George Orwell     4.7  10.99
7                           The Alchemist         Paulo Coelho     4.6  14.00
8                        The Great Gatsby  F. Scott Fitzgerald     4.6  11.50
9                          Fahrenheit 451         Ray Bradbury     4.5   9.50
10                      Wuthering Heights         Emily Bronte     4.5   9.50
11                        Brave New World        Aldous Huxley     4.4  11.99
12                      The Da Vinci Code            Dan Brown     4.3  16.50
13                 The Catcher in the Rye        J.D. Salinger     4.2  10.50
14                              Moby-Dick      Herman Melville     4.1  13.99

In [49]:
df=pd.read_sql_query("SELECT title ,author,rating,price FROM books ORDER BY rating DESC,Price ;",conn)
df

                                    title               author  rating  price
0                     Pride and Prejudice          Jane Austen     4.9   9.99
1                              The Hobbit       J.R.R. Tolkien     4.9  15.00
2   Harry Potter and the Sorcerer's Stone         J.K. Rowling     4.9  18.99
3                             Animal Farm        George Orwell     4.8   8.99
4                   To Kill a Mockingbird           Harper Lee     4.8  12.99
5                                    1984        George Orwell     4.7  10.99
6                               Jane Eyre     Charlotte Bronte     4.7  12.00
7                        The Great Gatsby  F. Scott Fitzgerald     4.6  11.50
8                           The Alchemist         Paulo Coelho     4.6  14.00
9                          Fahrenheit 451         Ray Bradbury     4.5   9.50
10                      Wuthering Heights         Emily Bronte     4.5   9.50
11                        Brave New World        Aldous Huxley     4.4  11.99
12                      The Da Vinci Code            Dan Brown     4.3  16.50
13                 The Catcher in the Rye        J.D. Salinger     4.2  10.50
14                              Moby-Dick      Herman Melville     4.1  13.99

In [54]:
agg_func=pd.read_sql_query("SELECT AVG(price) AS RATING  FROM books;",conn)ac
agg_func

      RATING
0  12.428667

In [58]:
agg_func=pd.read_sql_query("SELECT ROUND(AVG(price), 2) AS avg_price FROM books;",conn)
agg_func

   avg_price
0      12.43

In [62]:
agg_func=pd.read_sql_query("SELECT title, AVG(price),Min(rating)  FROM books;",conn)
agg_func

       title  AVG(price)  Min(rating)
0  Moby-Dick   12.428667          4.1

In [63]:
agg_func=pd.read_sql_query("SELECT COUNT(author) FROM books;",conn)
agg_func

   COUNT(author)
0             15

In [66]:
agg_func=pd.read_sql_query("SELECT COUNT(DISTINCT author) FROM books;",conn)
agg_func

   COUNT(DISTINCT author)
0                      14

In [67]:
agg_func=pd.read_sql_query("SELECT author FROM books;",conn)
agg_func

                 author
0            Harper Lee
1         George Orwell
2   F. Scott Fitzgerald
3           Jane Austen
4       Herman Melville
5         J.D. Salinger
6        J.R.R. Tolkien
7          Ray Bradbury
8      Charlotte Bronte
9         George Orwell
10         Paulo Coelho
11            Dan Brown
12         J.K. Rowling
13        Aldous Huxley
14         Emily Bronte

In [4]:
import sqlite3
import pandas as pd

# Connect to your database file (must be in the same folder as your notebook)
conn = sqlite3.connect("books.db")

# Create a cursor object to execute SQL commands
cursor = conn.cursor()

print("✅ Database connected successfully!")

✅ Database connected successfully!

In [5]:
df=pd.read_sql_query("SELECT * FROM books;",conn)
df

,book_id,title,author,genre,year_published,price,rating,publisher,available_copies
0,1,To Kill a Mockingbird,Harper Lee,Fiction,1960,12.99,4.8,J.B. Lippincott & Co.,5
1,2,1984,George Orwell,Dystopian,1949,10.99,4.7,Secker & Warburg,8
2,3,The Great Gatsby,F. Scott Fitzgerald,Classic,1925,11.50,4.6,Charles Scribner's Sons,3
3,4,Pride and Prejudice,Jane Austen,Romance,1813,9.99,4.9,T. Egerton,6
4,5,Moby-Dick,Herman Melville,Adventure,1851,13.99,4.1,Harper & Brothers,4
5,6,The Catcher in the Rye,J.D. Salinger,Fiction,1951,10.50,4.2,"Little, Brown and Company",7
6,7,The Hobbit,J.R.R. Tolkien,Fantasy,1937,15.00,4.9,George Allen & Unwin,10
7,8,Fahrenheit 451,Ray Bradbury,Science Fiction,1953,9.50,4.5,Ballantine Books,9
8,9,Jane Eyre,Charlotte Bronte,Romance,1847,12.00,4.7,"Smith, Elder & Co.",5
9,10,Animal Farm,George Orwell,Satire,1945,8.99,4.8,Secker & Warburg,12
10,11,The Alchemist,Paulo Coelho,Philosophy,1988,14.00,4.6,HarperTorch,11
11,12,The Da Vinci Code,Dan Brown,Thriller,2003,16.50,4.3,Doubleday,14
12,13,Harry Potter and the Sorcerer's Stone,J.K. Rowling,Fantasy,1997,18.99,4.9,Bloomsbury,20
13,14,Brave New World,Aldous Huxley,Dystopian,1932,11.99,4.4,Chatto & Windus,8
14,15,Wuthering Heights,Emily Bronte,Romance,1847,9.50,4.5,Thomas Cautley Newby,6

In [6]:
# Query to list all tables
cursor.execute("SELECT name FROM sqlite_master WHERE type='table';")

# Fetch all results
tables = cursor.fetchall()

print("Tables in the database:")
for table in tables:
    print(table[0])

Tables in the database:
books

In [5]:
import sqlite3
import pandas as pd

# Connect to the database
conn = sqlite3.connect(r"E:\ds_roadmap\dataset\updated_books.db")

# View authors table
authors = pd.read_sql_query("SELECT * FROM authors;", conn)
authors

   author_id                name  birth_year nationality
0          1        J.K. Rowling        1965     British
1          2  George R.R. Martin        1948    American
2          3     Haruki Murakami        1949    Japanese

In [24]:
df=pd.read_sql_query("SELECT * FROM publishers;",conn)
df

   publisher_id          name  location
0             1    Bloomsbury    London
1             2  Bantam Books  New York
2             3    Shinchosha     Tokyo

In [29]:
subquery=pd.read_sql_query("""SELECT name,location FROM publishers 
WHERE publisher_id=(
SELECT author_id FROM authors 
WHERE name = 'J.K. Rowling');""",conn)
subquery

         name location
0  Bloomsbury   London

In [7]:
df=pd.read_sql_query("""SELECT category_name FROM categories
WHERE category_id=(
SELECT book_id From books 
WHERE title='A Game of Thrones'
);""",conn)
df

      category_name
0  Literary Fiction

In [9]:
import sqlite3
import pandas as pd

# Connect to the database
conn = sqlite3.connect(r"E:\ds_roadmap\dataset\books_authors.db")

In [11]:
df=pd.read_sql_query("SELECT * FROM Author;",conn)
df

   author_id author_name   country
0          1    Ali Khan  Pakistan
1          2  Sara Ahmed        UK
2          3  Ahmed Raza     India
3          4   Zara Noor       USA
4          5  John Smith    Canada

In [12]:
df=pd.read_sql_query("SELECT * FROM Book;",conn)
df

   book_id             book_name        genre
0       10         Python Basics  Programming
1       11         AI Revolution   Technology
2       12  Data Science Secrets      Science
3       13        Creative Minds   Motivation

In [15]:
df=pd.read_sql_query("""SELECT author_name FROM Author WHERE author_id IN (
  SELECT author_id FROM Authored 
  WHERE book_id = (
  SELECT book_id FROM Book WHERE book_name='Python Basics'
  )) ;""",conn)
df

  author_name
0    Ali Khan
1  Sara Ahmed
2  Ahmed Raza

In [19]:
df=pd.read_sql_query("""SELECT author_name FROM Author 
WHERE author_id IN (
    SELECT author_id FROM Authored
    WHERE book_id=(
        SELECT book_id FROM Book
        Where genre= 'Technology'	
));""",conn)
df

  author_name
0  Sara Ahmed
1   Zara Noor

In [1]:
import sqlite3
import pandas as pd

# Connect to the database
conn = sqlite3.connect(r"C:\Users\saima\Downloads\sealeopard.db")

In [4]:
df=pd.read_sql_query("SELECT * FROM migrants;",conn)
df

   id  mile            region
0   1   150     Antarctic Bay
1   2   230  South Polar Zone
2   3   180         Ice Ridge
3   4   200      Frozen Shore
4   6   250    Deep South Sea
5   7   300          Icy Gulf
6   8   120        Frozen Bay
7   9   275     Crystal Coast
8  10   400      Snowy Waters

In [5]:
df=pd.read_sql_query("SELECT * FROM migrants;",conn)
df

   id  mile            region
0   1   150     Antarctic Bay
1   2   230  South Polar Zone
2   3   180         Ice Ridge
3   4   200      Frozen Shore
4   6   250    Deep South Sea
5   7   300          Icy Gulf
6   8   120        Frozen Bay
7   9   275     Crystal Coast
8  10   400      Snowy Waters

In [6]:
df=pd.read_sql_query("SELECT * FROM leopards;",conn)
df

   id            name
0   1   Arctic Hunter
1   2      Ocean Claw
2   3    Wave Stalker
3   4      Frost Fang
4   5     Sea Whisper
5   6  Glacier Shadow

In [13]:
df=pd.read_sql_query("SELECT * FROM leopards JOIN migrants ON leopards.id= migrants.id;",conn)
df

   id            name  id  mile            region
0   1   Arctic Hunter   1   150     Antarctic Bay
1   2      Ocean Claw   2   230  South Polar Zone
2   3    Wave Stalker   3   180         Ice Ridge
3   4      Frost Fang   4   200      Frozen Shore
4   6  Glacier Shadow   6   250    Deep South Sea

In [14]:
df=pd.read_sql_query("""SELECT * FROM leopards
LEFT JOIN migrants ON leopards.id= migrants.id;""",conn)
df

   id            name   id   mile            region
0   1   Arctic Hunter  1.0  150.0     Antarctic Bay
1   2      Ocean Claw  2.0  230.0  South Polar Zone
2   3    Wave Stalker  3.0  180.0         Ice Ridge
3   4      Frost Fang  4.0  200.0      Frozen Shore
4   5     Sea Whisper  NaN    NaN              None
5   6  Glacier Shadow  6.0  250.0    Deep South Sea

In [15]:
df=pd.read_sql_query("""SELECT * FROM leopards
RIGHT JOIN migrants ON leopards.id= migrants.id;""",conn)
df

    id            name  id  mile            region
0  1.0   Arctic Hunter   1   150     Antarctic Bay
1  2.0      Ocean Claw   2   230  South Polar Zone
2  3.0    Wave Stalker   3   180         Ice Ridge
3  4.0      Frost Fang   4   200      Frozen Shore
4  6.0  Glacier Shadow   6   250    Deep South Sea
5  NaN            None   7   300          Icy Gulf
6  NaN            None   8   120        Frozen Bay
7  NaN            None   9   275     Crystal Coast
8  NaN            None  10   400      Snowy Waters

In [16]:
df=pd.read_sql_query("""SELECT * FROM leopards
FULL JOIN migrants ON leopards.id= migrants.id;""",conn)
df

    id            name    id   mile            region
0  1.0   Arctic Hunter   1.0  150.0     Antarctic Bay
1  2.0      Ocean Claw   2.0  230.0  South Polar Zone
2  3.0    Wave Stalker   3.0  180.0         Ice Ridge
3  4.0      Frost Fang   4.0  200.0      Frozen Shore
4  5.0     Sea Whisper   NaN    NaN              None
5  6.0  Glacier Shadow   6.0  250.0    Deep South Sea
6  NaN            None   7.0  300.0          Icy Gulf
7  NaN            None   8.0  120.0        Frozen Bay
8  NaN            None   9.0  275.0     Crystal Coast
9  NaN            None  10.0  400.0      Snowy Waters

In [17]:
df=pd.read_sql_query("""SELECT * FROM leopards
INNER JOIN migrants ON leopards.id= migrants.id;""",conn)
df

   id            name  id  mile            region
0   1   Arctic Hunter   1   150     Antarctic Bay
1   2      Ocean Claw   2   230  South Polar Zone
2   3    Wave Stalker   3   180         Ice Ridge
3   4      Frost Fang   4   200      Frozen Shore
4   6  Glacier Shadow   6   250    Deep South Sea

In [20]:
df=pd.read_sql_query("""SELECT * FROM leopards NATURAL JOIN migrants;""",conn)
df

   id            name  mile            region
0   1   Arctic Hunter   150     Antarctic Bay
1   2      Ocean Claw   230  South Polar Zone
2   3    Wave Stalker   180         Ice Ridge
3   4      Frost Fang   200      Frozen Shore
4   6  Glacier Shadow   250    Deep South Sea

In [1]:
import sqlite3
import pandas as pd

# Connect to the database
conn = sqlite3.connect(r"C:\Users\saima\Downloads\books (1).db")

In [2]:
df=pd.read_sql_query("SELECT * FROM translators;",conn)
df

   translator_id  translator_name  language
0              1  Haruki Murakami  Japanese
1              2      Emily Brown    French
2              3      Maria Lopez   Spanish
3              4       John Smith   English

In [4]:
df=pd.read_sql_query("SELECT * FROM authors;",conn)
df

   author_id             author_name   country
0          1           George Orwell        UK
1          2  Gabriel García Márquez  Colombia
2          3         Haruki Murakami     Japan
3          4             Jane Austen        UK
4          5              Mark Twain       USA

In [10]:
df=pd.read_sql_query("""SELECT author_name FROM authors
UNION
SELECT translator_name FROM translators;""",
conn)
df

              author_name
0             Emily Brown
1  Gabriel García Márquez
2           George Orwell
3         Haruki Murakami
4             Jane Austen
5              John Smith
6             Maria Lopez
7              Mark Twain

In [11]:
df=pd.read_sql_query("""SELECT author_name FROM authors
INTERSECT
SELECT translator_name FROM translators;""",
conn)
df

       author_name
0  Haruki Murakami

In [12]:
df=pd.read_sql_query("""SELECT author_name FROM authors
EXCEPT
SELECT translator_name FROM translators;""",
conn)
df

              author_name
0  Gabriel García Márquez
1           George Orwell
2             Jane Austen
3              Mark Twain

In [13]:
import sqlite3
import pandas as pd

# Connect to the database
conn = sqlite3.connect(r"C:\Users\saima\Downloads\ratings.db")

In [14]:
df=pd.read_sql_query("""
SELECT book_id FROM book_ratings;
""",conn)
df

   book_id
0        1
1        1
2        2
3        3
4        3
5        4
6        5
7        6
8        6

In [15]:
df=pd.read_sql_query("""
SELECT rating FROM book_ratings;
""",conn)
df

   rating
0     4.8
1     4.5
2     4.2
3     4.9
4     5.0
5     4.6
6     4.7
7     4.3
8     4.0

In [23]:
df=pd.read_sql_query("""
SELECT AVG(rating) AS AVERAGE FROM book_ratings
GROUP BY
book_id
HAVING
AVERAGE > 4.2;
""",conn)
df

   AVERAGE
0     4.65
1     4.95
2     4.60
3     4.70

In [25]:
df=pd.read_sql_query("""
SELECT COUNT(rating) AS AVERAGE FROM book_ratings
GROUP BY
book_id
;
""",conn)
df

   AVERAGE
0        2
1        1
2        2
3        1
4        1
5        2

In [37]:
import sqlite3
import pandas as pad
df=pd.read_excel("practice.xlsx")
conn = sqlite3.connect("df")
df.to_sql("practice",conn,if_exists="replace",index=False)
F=pd.read_sql_query("SELECT * FROM practice",conn)

   user_id first_name last_name                email  age         city
0        1      Alice     Smith    alice@example.com   25     New York
1        2        Bob     Jones      bob@example.com   30  Los Angeles
2        3    Charlie     Brown  charlie@example.com   35      Chicago
3        4      David    Wilson    david@example.com   28      Houston
4        5        Eva    Taylor      eva@example.com   22      Phoenix

In [42]:
u=pd.read_sql_query("SELECT first_name FROM practice",conn)
u

  first_name
0      Alice
1        Bob
2    Charlie
3      David
4        Eva

In [43]:
u=pd.read_sql_query("SELECT last_name FROM practice WHERE age>25",conn)
u

  last_name
0     Jones
1     Brown
2    Wilson

In [45]:
u=pd.read_sql_query("SELECT first_name FROM practice where age BETWEEN 20 AND 28",conn)
u

  first_name
0      Alice
1      David
2        Eva

In [21]:
import sqlite3

# Create a database connection (or create the database file)
conn = sqlite3.connect('mydatabase.db')

In [45]:
conn.execute("""
CREATE TABLE profile2(
    ID INTEGER,
    NAME TEXT,
    AGE INTEGER,
    SECTION TEXT,
    PRIMARY KEY(ID)
)
""")
conn.commit()

OperationalError: table profile2 already exists

In [55]:
conn.execute("""
CREATE TABLE setting1(
    ID INTEGER,
    NAME TEXT NOT NULL,
    password BLOB UNIQUE,
    PRIMARY KEY(ID),
    FOREIGN KEY("NAME") REFERENCES profile2(NAME)
    )
    """)
conn.commit()

In [68]:
conn.executescript(
    """
CREATE TABLE CARD4(
    ID INTEGER

    
    );
    
CREATE TABLE STATION6(
    ID INTEGER NOT NULL,
    NAME TEXT NOT NULL UNIQUE,
    LINE NUMERIC CHECK(LINE>=0),
    PRIMARY KEY (ID)
    );
    
CREATE TABLE SWIPE5(
    ID INTEGER NOT NULL,
    CARD_ID INTEGER NOT NULL,
    STATION INTEGER NOT NULL,
    TYPE TEXT CHECK (TYPE IN ("EXIT","ENTER","REMOVE"))
    
    );

    """
)

In [70]:
conn.executescript("""
CREATE TABLE CARD (
    ID INTEGER PRIMARY KEY
);

CREATE TABLE STATION1 (
    ID INTEGER NOT NULL,
    NAME TEXT NOT NULL UNIQUE,
    LINE NUMERIC CHECK (LINE >= 0),
    PRIMARY KEY (ID)
);

CREATE TABLE SWIPE (
    ID INTEGER NOT NULL,
    CARD_ID INTEGER NOT NULL,
    STATION INTEGER NOT NULL,
    TYPE TEXT CHECK (TYPE IN ('EXIT','ENTER','REMOVE')),
    PRIMARY KEY (ID)
);
ALTER TABLE SWIPE RENAME TO SWIPECARD
""")

OperationalError: table CARD already exists

In [75]:
conn.executescript(
    """
    ALTER TABLE SWIPE RENAME TO SWIPE_CARD
    """
)

OperationalError: no such table: SWIPE

In [76]:
conn.executescript(
    """
    """
)

In [83]:
import sqlite3
import pandas as pd
conn=sqlite3.connect("own_data.db")

In [86]:
conn.execute("""
CREATE TABLE data(
ID INTEGER,
NAME TEXT NOT NULL UNIQUE,
AGE INTEGER,
PRIMARY KEY(ID)
    );
    """
)

In [88]:
conn.commit()

In [91]:
conn.execute(
    """
INSERT INTO data(NAME,AGE)
VALUES
("SAIM",22),
("AYAZ",24),
("ANWAR",24)
    """
)

IntegrityError: UNIQUE constraint failed: data.NAME

In [92]:
conn.commit()

In [94]:
df=pd.read_sql("SELECT * FROM data",conn)
df

   ID   NAME  AGE
0   1   SAIM   22
1   2   AYAZ   24
2   3  ANWAR   24

In [153]:
import sqlite3
import pandas as pd
df=pd.read_csv('Bank.csv')

   id    name  balance     password  total_period
0   1     Ali     5000      pass123            12
1   2    Sara    12000    secret456            24
2   3    Omar     8000    myPass789            18
3   4    Hina    15000  hinapass321            36
4   5    Zain     7000     zpass987             6
5   6  Ayesha    20000    ayesha123            48
6   7   Fahad     9500     fahad999            30

In [154]:
conn=sqlite3.connect('bankdata.db')

In [159]:
df.to_sql('DATA', conn, if_exists='replace', index=False)

7

In [160]:
pd.read_sql_query("SELECT * FROM DATA",conn)

   id    name  balance     password  total_period
0   1     Ali     5000      pass123            12
1   2    Sara    12000    secret456            24
2   3    Omar     8000    myPass789            18
3   4    Hina    15000  hinapass321            36
4   5    Zain     7000     zpass987             6
5   6  Ayesha    20000    ayesha123            48
6   7   Fahad     9500     fahad999            30

In [161]:
pd.read_sql_query("SELECT name FROM DATA",conn)

     name
0     Ali
1    Sara
2    Omar
3    Hina
4    Zain
5  Ayesha
6   Fahad

In [163]:
import sqlite3
conn =sqlite3.connect('library.db')

In [167]:
import pandas as pd
df=pd.read_csv('libarary_data.csv')
df

,BookID,Title,Author,Genre,Year,Available
0,1,Python Basics,John Smith,Programming,2020,Yes
1,2,Data Science 101,Alice Johnson,Data Science,2019,No
2,3,Machine Learning Guide,Michael Brown,AI,2021,Yes
3,4,SQL for Beginners,Laura Wilson,Database,2018,Yes
4,5,Advanced Python,David Lee,Programming,2022,No
5,6,Statistics Made Easy,Emma Davis,Statistics,2020,Yes
6,7,Deep Learning Fundamentals,Robert Taylor,AI,2021,Yes
7,8,Excel for Everyone,Susan Miller,Office,2017,No

In [169]:
df.to_sql('profile',conn,if_exists='append',index=False)

8

In [171]:
pd.read_sql_query("SELECT * FROM profile",conn)

,BookID,Title,Author,Genre,Year,Available
0,1,Python Basics,John Smith,Programming,2020,Yes
1,2,Data Science 101,Alice Johnson,Data Science,2019,No
2,3,Machine Learning Guide,Michael Brown,AI,2021,Yes
3,4,SQL for Beginners,Laura Wilson,Database,2018,Yes
4,5,Advanced Python,David Lee,Programming,2022,No
5,6,Statistics Made Easy,Emma Davis,Statistics,2020,Yes
6,7,Deep Learning Fundamentals,Robert Taylor,AI,2021,Yes
7,8,Excel for Everyone,Susan Miller,Office,2017,No

In [173]:
pd.read_sql_query("SELECT Title,Genre FROM profile WHERE Year != 2020 AND Available = 'Yes'",conn)

                        Title     Genre
0      Machine Learning Guide        AI
1           SQL for Beginners  Database
2  Deep Learning Fundamentals        AI

In [180]:
import sqlite3
import pandas as pd
df=pd.read_csv('libarary_data.csv')
df

,BookID,Title,Author,Genre,Year,Available
0,1,Python Basics,John Smith,Programming,2020,Yes
1,2,Data Science 101,Alice Johnson,Data Science,2019,No
2,3,Machine Learning Guide,Michael Brown,AI,2021,Yes
3,4,SQL for Beginners,Laura Wilson,Database,2018,Yes
4,5,Advanced Python,David Lee,Programming,2022,No
5,6,Statistics Made Easy,Emma Davis,Statistics,2020,Yes
6,7,Deep Learning Fundamentals,Robert Taylor,AI,2021,Yes
7,8,Excel for Everyone,Susan Miller,Office,2017,No

In [182]:
conn=sqlite3.connect("data.db")
conn.commit()

In [183]:
conn.execute(
    """
    CREATE TEMP TABLE T_D(
    BOOKID,
    TITLE,
    AUTHOR,
    GENRE,
    YEAR,
    AVAILABLE
    )

    """
)

In [185]:
df.to_sql('T_D',conn,if_exists='append',index=False)

8

In [187]:
pd.read_sql_query(
    "SELECT * FROM T_D",conn
)

,BOOKID,TITLE,AUTHOR,GENRE,YEAR,AVAILABLE
0,1,Python Basics,John Smith,Programming,2020,Yes
1,2,Data Science 101,Alice Johnson,Data Science,2019,No
2,3,Machine Learning Guide,Michael Brown,AI,2021,Yes
3,4,SQL for Beginners,Laura Wilson,Database,2018,Yes
4,5,Advanced Python,David Lee,Programming,2022,No
5,6,Statistics Made Easy,Emma Davis,Statistics,2020,Yes
6,7,Deep Learning Fundamentals,Robert Taylor,AI,2021,Yes
7,8,Excel for Everyone,Susan Miller,Office,2017,No

In [189]:
conn.execute(
    """
    CREATE TABLE D_T(
    BOOKID INTEGER NOT NULL,
    TITLE TEXT NOT NULL,
    GENRE TEXT NOT NULL,
    YEAR TEXT NOT NULL,
    AVAILABLE
    )
    """
)

In [192]:
conn.execute(
    """
    INSERT INTO D_T(BOOKID,TITLE,GENRE,YEAR,AVAILABLE)
    SELECT BOOKID,TITLE,GENRE,YEAR,AVAILABLE FROM T_D;
    """
)

In [193]:
conn.commit()

In [194]:
pd.read_sql_query("SELECT * FROM D_T",conn)

   BOOKID                       TITLE         GENRE  YEAR AVAILABLE
0       1               Python Basics   Programming  2020       Yes
1       2            Data Science 101  Data Science  2019        No
2       3      Machine Learning Guide            AI  2021       Yes
3       4           SQL for Beginners      Database  2018       Yes
4       5             Advanced Python   Programming  2022        No
5       6        Statistics Made Easy    Statistics  2020       Yes
6       7  Deep Learning Fundamentals            AI  2021       Yes
7       8          Excel for Everyone        Office  2017        No

In [197]:
conn.execute("""
DELETE FROM D_T WHERE GENRE='AI'
""")

In [207]:
# in the delete command the main thing to give attention is that during delete command yu have to del the foregin key manually first or used on delete cascade that automatically delete the that id other wise it casues error to yu

In [198]:
pd.read_sql_query("SELECT * FROM D_T",conn)

   BOOKID                 TITLE         GENRE  YEAR AVAILABLE
0       1         Python Basics   Programming  2020       Yes
1       2      Data Science 101  Data Science  2019        No
2       4     SQL for Beginners      Database  2018       Yes
3       5       Advanced Python   Programming  2022        No
4       6  Statistics Made Easy    Statistics  2020       Yes
5       8    Excel for Everyone        Office  2017        No

In [202]:
conn.execute(
    """
    UPDATE D_T SET TITLE='DATA SCIENCE'
    WHERE BOOKID=2
    """
)
pd.read_sql_query("SELECT * FROM D_T",conn)

   BOOKID                 TITLE         GENRE  YEAR AVAILABLE
0       1         Python Basics   Programming  2020       Yes
1       2          DATA SCIENCE  Data Science  2019        No
2       4     SQL for Beginners      Database  2018       Yes
3       5       Advanced Python   Programming  2022        No
4       6  Statistics Made Easy    Statistics  2020       Yes
5       8    Excel for Everyone        Office  2017        No

In [ ]:
#and here in the update yu have yo make sure that yu applied the where condition other wise it applied on all the rows

In [210]:
import sqlite3

conn = sqlite3.connect("library.db")
cur = conn.cursor()

# Enable foreign keys
cur.execute("PRAGMA foreign_keys = ON;")

# Drop tables if already exist
cur.executescript("""
DROP TABLE IF EXISTS purchase;
DROP TABLE IF EXISTS books;
DROP TABLE IF EXISTS profile;
""")

# Create profile table
cur.execute("""
CREATE TABLE profile (
    user_id INTEGER PRIMARY KEY,
    name TEXT NOT NULL,
    email TEXT UNIQUE,
    role TEXT
);
""")

# Create books table
cur.execute("""
CREATE TABLE books (
    book_id INTEGER PRIMARY KEY,
    title TEXT NOT NULL,
    author TEXT,
    price INTEGER,
    stock INTEGER
);
""")

# Create purchase table
cur.execute("""
CREATE TABLE purchase (
    purchase_id INTEGER PRIMARY KEY,
    user_id INTEGER,
    book_id INTEGER,
    purchase_date TEXT,
    FOREIGN KEY (user_id) REFERENCES profile(user_id),
    FOREIGN KEY (book_id) REFERENCES books(book_id)
);
""")

# Insert data into profile
cur.executescript("""
INSERT INTO profile VALUES (1,'Ali','ali@gmail.com','student');
INSERT INTO profile VALUES (2,'Sara','sara@gmail.com','student');
INSERT INTO profile VALUES (3,'Admin','admin@gmail.com','admin');
""")

# Insert data into books
cur.executescript("""
INSERT INTO books VALUES (101,'Python Basics','John Smith',1500,5);
INSERT INTO books VALUES (102,'Data Science','Andrew Lee',2000,2);
INSERT INTO books VALUES (103,'Machine Learning','Tom Hardy',2500,0);
""")

# Insert data into purchase
cur.executescript("""
INSERT INTO purchase VALUES (1,1,101,'2026-01-01');
INSERT INTO purchase VALUES (2,2,102,'2026-01-02');
""")

conn.commit()


print("✅ Library dataset created successfully")

✅ Library dataset created successfully

In [211]:
pd.read_sql_query("SELECT * FROM books",conn)

   book_id             title      author  price  stock
0      101     Python Basics  John Smith   1500      5
1      102      Data Science  Andrew Lee   2000      2
2      103  Machine Learning   Tom Hardy   2500      0

In [212]:
pd.read_sql_query("SELECT * FROM profile",conn)

   user_id   name            email     role
0        1    Ali    ali@gmail.com  student
1        2   Sara   sara@gmail.com  student
2        3  Admin  admin@gmail.com    admin

In [213]:
pd.read_sql_query("SELECT * FROM purchase",conn)

   purchase_id  user_id  book_id purchase_date
0            1        1      101    2026-01-01
1            2        2      102    2026-01-02

In [219]:
conn.execute(
    """
    CREATE TRIGGER STOCK2
    BEFORE INSERT ON purchase
    FOR EACH ROW
    BEGIN
        SELECT CASE
            WHEN (SELECT STOCK FROM books WHERE book_id=NEW.book_id )=0
            THEN RAISE(ABORT,"STOCK RUK DO")
    END;
    END;
    """
)

In [9]:
conn.execute("""
    CREATE TRIGGER PURCHASE
    AFTER INSERT ON purchase
    FOR EACH ROW
    BEGIN
        UPDATE books
        SET stock=stock-1
        WHERE book_id=NEW=book_id;
    END;
    
""")

OperationalError: no such table: main.purchase

In [11]:
import sqlite3
import pandas as pd
conn = sqlite3.connect("shop.db")
cursor = conn.cursor()

In [91]:
cursor.executescript("""
CREATE TABLE IF NOT EXISTS users (
    id INTEGER PRIMARY KEY,
    name TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS products (
    id INTEGER PRIMARY KEY,
    title TEXT NOT NULL,
    price INTEGER
);

CREATE TABLE IF NOT EXISTS orders (
    id INTEGER PRIMARY KEY,
    user_id INTEGER,
    product_id INTEGER,
    quantity INTEGER,
    FOREIGN KEY (user_id) REFERENCES users(id),
    FOREIGN KEY (product_id) REFERENCES products(id)
);

CREATE TABLE IF NOT EXISTS logs (
    id INTEGER PRIMARY KEY,
    message TEXT
);
""")

conn.commit()

In [92]:
cursor.executescript("""
INSERT INTO users (name) VALUES ('Ali');
INSERT INTO users (name) VALUES ('Ayan');

INSERT INTO products (title, price) VALUES ('Laptop', 120000);
INSERT INTO products (title, price) VALUES ('Mouse', 2000);

INSERT INTO orders (user_id, product_id, quantity)
VALUES (1, 1, 1);

INSERT INTO orders (user_id, product_id, quantity)
VALUES (2, 2, 2);
""")

conn.commit()

In [93]:
pd.read_sql_query("SELECT * FROM orders",conn)

    id  user_id  product_id  quantity
0    2        2           2         2
1    3        5           5         5
2    4        5           5         5
3    5        5           5         5
4    6        5           5         5
5    7        5           5         5
6    8        5           5         5
7    9        5           5         5
8   10        1           1         1
9   11        2           2         2
10  12        1           1         1
11  13        2           2         2
12  14        1           1         1
13  15        2           2         2
14  16        1           1         1
15  17        2           2         2
16  18        1           1         1
17  19        2           2         2
18  20        1           1         1
19  21        2           2         2
20  22        1           1         1
21  23        2           2         2
22  24        1           1         1
23  25        2           2         2
24  26        1           1         1
25  27        2           2         2

In [94]:
pd.read_sql_query("SELECT * FROM products",conn)

    id   title   price
0    1  Laptop  120000
1    2   Mouse    2000
2    3  Laptop  120000
3    4   Mouse    2000
4    5  Laptop  120000
5    6   Mouse    2000
6    7  Laptop  120000
7    8   Mouse    2000
8    9  Laptop  120000
9   10   Mouse    2000
10  11  Laptop  120000
11  12   Mouse    2000
12  13  Laptop  120000
13  14   Mouse    2000
14  15  Laptop  120000
15  16   Mouse    2000
16  17  Laptop  120000
17  18   Mouse    2000
18  19  Laptop  120000
19  20   Mouse    2000

In [24]:
cursor.executescript("""
CREATE TRIGGER IF NOT EXISTS order_deleted
AFTER DELETE ON orders
FOR EACH ROW
BEGIN
    INSERT INTO logs (message)
    VALUES ('Order deleted for user_id = ' || OLD.user_id);
END;
""")

conn.commit()

In [25]:
cursor.execute("DELETE FROM orders WHERE id = 1")
conn.commit()

In [26]:
pd.read_sql("SELECT * FROM logs", conn)

   id                        message
0   1  Order deleted for user_id = 1

In [39]:
cursor.executescript(
    """
    CREATE TRIGGER IF NOT EXISTS NEW_ORDER
    AFTER INSERT ON orders
    FOR EACH ROW
    BEGIN
        INSERT INTO logs(message)
        VALUES('new order created'||NEW.user_id);
    END;
    """)

In [40]:
conn.commit()

In [50]:
cursor.execute(
    """
   INSERT INTO orders (user_id, product_id, quantity)
    VALUES (5, 5, 5);
    """
)
conn.commit()

In [51]:
pd.read_sql_query("SELECT * FROM logs",conn)

   id                        message
0   1  Order deleted for user_id = 1
1   2             new order created5
2   3             new order created5
3   4             new order created5
4   5             new order created5
5   6             new order created5
6   7             new order created5
7   8             new order created5

In [129]:
cursor.executescript(
"""
CREATE TRIGGER IF NOT EXISTS DEL_kea
AFTER DELETE ON products
FOR EACH ROW
BEGIN
    INSERT INTO logs(message)
    VALUES ('DEL KE HOI PRODUCT NAME = ' || OLD.title);
END;
"""
)
conn.commit()

In [126]:
cursor.execute("PRAGMA table_info(logs)")
pd.DataFrame(cursor.fetchall(), columns=["cid","name","type","notnull","dflt_value","pk"])

   cid     name     type  notnull dflt_value  pk
0    0       id  INTEGER        0       None   1
1    1  message     TEXT        0       None   0

In [130]:
cursor.execute("DROP TRIGGER IF EXISTS DEL_kea")
conn.commit()

In [131]:
cursor.executescript("""
CREATE TRIGGER DEL_kea
AFTER DELETE ON products
FOR EACH ROW
BEGIN
    INSERT INTO logs(message)
    VALUES ('DEL KE HOI PRODUCT NAME = ' || OLD.title);
END;
""")
conn.commit()

In [132]:
cursor.execute("DELETE FROM products WHERE price = 2000")
conn.commit()

In [133]:
pd.read_sql_query("SELECT * FROM logs",conn)

    id                          message
0    1    Order deleted for user_id = 1
1    2               new order created5
2    3               new order created5
3    4               new order created5
4    5               new order created5
5    6               new order created5
6    7               new order created5
7    8               new order created5
8    9               new order created1
9   10               new order created2
10  11               new order created1
11  12               new order created2
12  13               new order created1
13  14               new order created2
14  15               new order created1
15  16               new order created2
16  17               new order created1
17  18               new order created2
18  19               new order created1
19  20               new order created2
20  21               new order created1
21  22               new order created2
22  23               new order created1
23  24               new order created2
24  25               new order created1
25  26               new order created2
26  27  DEL KE HOI PRODUCT NAME = Mouse
27  28  DEL KE HOI PRODUCT NAME = Mouse
28  29  DEL KE HOI PRODUCT NAME = Mouse
29  30  DEL KE HOI PRODUCT NAME = Mouse
30  31  DEL KE HOI PRODUCT NAME = Mouse
31  32  DEL KE HOI PRODUCT NAME = Mouse
32  33  DEL KE HOI PRODUCT NAME = Mouse
33  34  DEL KE HOI PRODUCT NAME = Mouse
34  35  DEL KE HOI PRODUCT NAME = Mouse
35  36  DEL KE HOI PRODUCT NAME = Mouse

In [134]:
import sqlite3
import pandas as pd

conn = sqlite3.connect("cs50_practice.db")
cursor = conn.cursor()

In [135]:
# USERS TABLE
cursor.executescript("""
CREATE TABLE IF NOT EXISTS users (
    id INTEGER PRIMARY KEY,
    name TEXT,
    email TEXT
);

CREATE TABLE IF NOT EXISTS products (
    id INTEGER PRIMARY KEY,
    title TEXT,
    price INTEGER,
    category TEXT
);

CREATE TABLE IF NOT EXISTS orders (
    id INTEGER PRIMARY KEY,
    user_id INTEGER,
    product_id INTEGER,
    quantity INTEGER,
    FOREIGN KEY(user_id) REFERENCES users(id),
    FOREIGN KEY(product_id) REFERENCES products(id)
);

CREATE TABLE IF NOT EXISTS logs (
    id INTEGER PRIMARY KEY,
    message TEXT
);
""")
conn.commit()

In [136]:
# USERS
cursor.executescript("""
INSERT INTO users (name, email) VALUES
('Ali', 'ali@example.com'),
('Ayan', 'ayan@example.com'),
('Sara', 'sara@example.com');
""")

# PRODUCTS
cursor.executescript("""
INSERT INTO products (title, price, category) VALUES
('Laptop', 120000, 'Electronics'),
('Mouse', 2000, 'Electronics'),
('Chair', 5000, 'Furniture'),
('Desk', 12000, 'Furniture'),
('Headphones', 8000, 'Electronics');
""")

# ORDERS
cursor.executescript("""
INSERT INTO orders (user_id, product_id, quantity) VALUES
(1, 1, 1),
(1, 2, 2),
(2, 3, 1),
(2, 5, 1),
(3, 4, 1),
(3, 2, 1);
""")
conn.commit()

In [143]:
pd.read_sql_query("SELECT * FROM  products",conn)

   id       title   price     category
0   1      Laptop  120000  Electronics
1   2       Mouse    2000  Electronics
2   3       Chair    5000    Furniture
3   4        Desk   12000    Furniture
4   5  Headphones    8000  Electronics

In [137]:
cursor.execute(
    """
    CREATE VIEW EXPENSIVE_PROD AS
    SELECT * FROM products where price > 5000
    """
)

In [139]:
conn.commit()

In [140]:
pd.read_sql_query("SELECT * FROM EXPENSIVE_PROD",conn)

   id       title   price     category
0   1      Laptop  120000  Electronics
1   4        Desk   12000    Furniture
2   5  Headphones    8000  Electronics

In [147]:
cursor.execute("SELECT name FROM sqlite_master WHERE type='table';")
tables = cursor.fetchall()

In [148]:
for table_name in tables:
    table_name = table_name[0]  # get the name from the tuple
    print(f"\nSchema for table: {table_name}")
    cursor.execute(f"PRAGMA table_info({table_name});")
    schema = cursor.fetchall()
    for column in schema:
        print(column)

Schema for table: users
(0, 'id', 'INTEGER', 0, None, 1)
(1, 'name', 'TEXT', 0, None, 0)
(2, 'email', 'TEXT', 0, None, 0)

Schema for table: products
(0, 'id', 'INTEGER', 0, None, 1)
(1, 'title', 'TEXT', 0, None, 0)
(2, 'price', 'INTEGER', 0, None, 0)
(3, 'category', 'TEXT', 0, None, 0)

Schema for table: orders
(0, 'id', 'INTEGER', 0, None, 1)
(1, 'user_id', 'INTEGER', 0, None, 0)
(2, 'product_id', 'INTEGER', 0, None, 0)
(3, 'quantity', 'INTEGER', 0, None, 0)

Schema for table: logs
(0, 'id', 'INTEGER', 0, None, 1)
(1, 'message', 'TEXT', 0, None, 0)

In [165]:
cursor.execute("""
CREATE VIEW useable AS
SELECT users.name, products.title
FROM users
JOIN orders
    ON users.id = orders.user_id
JOIN products
    ON products.id = orders.product_id
""")
conn.commit()

In [166]:
conn.commit()

In [168]:
pd.read_sql_query("SELECT * FROM useable", conn)

   name       title
0   Ali      Laptop
1   Ali       Mouse
2  Ayan       Chair
3  Ayan  Headphones
4  Sara        Desk
5  Sara       Mouse

In [187]:
cursor.execute("""
CREATE VIEW summary2 AS
SELECT 
    u.id,
    u.name,
    SUM(o.quantity * p.price) AS total_spend
FROM users u
JOIN orders o ON u.id = o.user_id
JOIN products p ON o.product_id = p.id
GROUP BY u.id, u.name
""")
conn.commit()

In [188]:
conn.commit()

In [189]:
pd.read_sql_query("SELECT * FROM summary2", conn)

   id  name  total_spend
0   1   Ali       124000
1   2  Ayan        13000
2   3  Sara        14000

In [178]:
pd.read_sql("SELECT * FROM orders", conn)

   id  user_id  product_id  quantity
0   1        1           1         1
1   2        1           2         2
2   3        2           3         1
3   4        2           5         1
4   5        3           4         1
5   6        3           2         1

In [ ]:
cursor.execute(
    """
    CREATE TEMP VIEW AS temp_summary2
    SELECT total_spend ,name FROM summary2 WHERE total_spend>13000 
    
""")

In [193]:
pd.read_sql_query("SELECT * FROM temp_summary2",conn)

   total_spend  name
0       124000   Ali
1        14000  Sara

In [219]:
cursor.execute(
    """
WITH use2 AS (
    SELECT 
    u.id,
    u.name,
    SUM(o.quantity * p.price) AS total_spend
FROM users u
JOIN orders o ON u.id = o.user_id
JOIN products p ON o.product_id = p.id
GROUP BY u.name
)
SELECT * FROM use2;

"""
)
rows = cursor.fetchall()

for row in rows:
    print(row)

(1, 'Ali', 124000)
(2, 'Ayan', 13000)
(3, 'Sara', 14000)

In [213]:
conn.commit()

In [ ]:
# window function

In [40]:
import sqlite3
import pandas as pd

conn = sqlite3.connect(":memory:")
cursor = conn.cursor()

# Table 1: Customers
cursor.execute("""
CREATE TABLE customers (
    id INTEGER PRIMARY KEY,
    name TEXT,
    region TEXT
)
""")

cursor.executemany("""
INSERT INTO customers (id, name, region) VALUES (?, ?, ?)
""", [
    (1, 'Alice', 'East'),
    (2, 'Bob', 'East'),
    (3, 'Carol', 'West'),
    (4, 'Dave', 'West'),
    (5, 'Eve', 'North'),
    (6, 'Frank', 'North')
])

# Table 2: Products
cursor.execute("""
CREATE TABLE products (
    id INTEGER PRIMARY KEY,
    name TEXT,
    price INTEGER
)
""")

cursor.executemany("""
INSERT INTO products (id, name, price) VALUES (?, ?, ?)
""", [
    (1, 'Laptop', 1000),
    (2, 'Phone', 500),
    (3, 'Tablet', 700)
])

# Table 3: Orders
cursor.execute("""
CREATE TABLE orders (
    id INTEGER PRIMARY KEY,
    customer_id INTEGER,
    product_id INTEGER,
    quantity INTEGER,
    FOREIGN KEY(customer_id) REFERENCES customers(id),
    FOREIGN KEY(product_id) REFERENCES products(id)
)
""")

cursor.executemany("""
INSERT INTO orders (customer_id, product_id, quantity) VALUES (?, ?, ?)
""", [
    (1, 1, 1),   # Alice buys 1 Laptop
    (1, 2, 2),   # Alice buys 2 Phones
    (2, 2, 1),   # Bob buys 1 Phone
    (3, 3, 2),   # Carol buys 2 Tablets
    (4, 2, 3),   # Dave buys 3 Phones
    (5, 1, 1),   # Eve buys 1 Laptop
    (6, 3, 1)    # Frank buys 1 Tablet
])

conn.commit()

In [41]:
query = """
SELECT 
    c.name AS customer,
    c.region,
    SUM(p.price * o.quantity) OVER(PARTITION BY c.name) AS total_spent
FROM orders o
JOIN customers c ON o.customer_id = c.id
JOIN products p ON o.product_id = p.id;
"""

df = pd.read_sql_query(query, conn)
df

  customer region  total_spent
0    Alice   East         2000
1    Alice   East         2000
2      Bob   East          500
3    Carol   West         1400
4     Dave   West         1500
5      Eve  North         1000
6    Frank  North          700

In [42]:
query = """
SELECT 
    c.name AS customer,
    c.region,
    SUM(p.price * o.quantity) AS amount,
    RANK() OVER(PARTITION BY c.region ORDER BY SUM(p.price * o.quantity) DESC) AS rank_in_region
FROM orders o
JOIN customers c ON o.customer_id = c.id
JOIN products p ON o.product_id = p.id
GROUP BY c.name, c.region;
"""

df = pd.read_sql_query(query, conn)
df

  customer region  amount  rank_in_region
0    Alice   East    2000               1
1      Bob   East     500               2
2      Eve  North    1000               1
3    Frank  North     700               2
4     Dave   West    1500               1
5    Carol   West    1400               2

In [43]:
cursor.execute("""
CREATE VIEW SECURE_V AS
    SELECT id,name,'anonymus' AS price
FROM products
""")

In [11]:
conn.commit()

In [44]:
pd.read_sql_query("SELECT * FROM SECURE_V",conn)

   id    name     price
0   1  Laptop  anonymus
1   2   Phone  anonymus
2   3  Tablet  anonymus

In [45]:
cursor.execute("""
ALTER TABLE products
ADD COLUMN deleted INTEGER DEFAULT 0;
""")

In [46]:
pd.read_sql_query("SELECT * FROM products",conn)

   id    name  price  deleted
0   1  Laptop   1000        0
1   2   Phone    500        0
2   3  Tablet    700        0

In [47]:
cursor.execute("""
        UPDATE  products SET deleted =1 where name = 'Laptop';
""")

In [22]:
conn.commit()

In [48]:
pd.read_sql_query("SELECT * FROM products where deleted=0",conn)

   id    name  price  deleted
0   2   Phone    500        0
1   3  Tablet    700        0

In [49]:
cursor.execute("""
    CREATE INDEX PROD_VIEW ON products('name');
               """)

In [50]:
conn.commit()

In [51]:

pd.read_sql_query("SELECT name FROM products WHERE name='Laptop'",conn)

     name
0  Laptop

In [52]:
cursor.execute(
    """
    CREATE INDEX PROD_VIEW2 ON products('name','price');
    """
)

In [54]:
pd.read_sql_query("SELECT name ,price  FROM products WHERE name='Laptop' AND price=1000",conn)

     name  price
0  Laptop   1000

In [55]:
cursor.execute("""
CREATE INDEX  PROD_PARTIAL_ONE ON products ('name','price') WHERE id=1;
""")